package fr.uge.map;

public enum ObstacleType {
	BED, BOG, BOMB, BRICK, CHAIR, CLIFF, DOOR, FENCE,
	FORT, GATE, HEDGE, HOUSE, HUSK, HUSKS, LOCK, MONITOR, 
	PIANO, PILLAR, PIPE, ROCK, RUBBLE,
	SHELL, SIGN, SPIKE, STATUE, STUMP, TABLE,
	TOWER, TREE, TREES, WALL
}
